### ISSUE TITLE
CTRL-J for enter?

### ISSUE THREAD

**Issue by yourealwaysbe** [jart/bestline#36]
Thanks for the library.

CTRL-J is a common shortcut for the enter key. Is it possible to add it to the supported shortcuts?

**Comment by jart** [comment]
So CTRL-J sends `\n` rather than `\r`. We might actually want to use CTRL-J for multi-line prompts, what do you think?

**Comment by yourealwaysbe** [comment]
Oh, i learned something today :)

I'm quite used to using ctrl-j in various terminals to execute a command. Ctrl-m turns out to be the shortcut for the enter key, i think.

Ctrl-m already works in bestline (or at least in gplaces), so i'm happy with that. Having ctrl-j for multi-line prompts seems reasonable. (I think ctrl-enter is another common way of doing thata.)

**Comment by jart** [comment]
Sadly CTRL-ENTER and ENTER send the same code, which is `'\r'`. I truly wish terminals made it possible to tell the two apart. ALT-ENTER is also sadly problematic, since it's oftentimes claimed by the tty for full screening the terminal window. I'm glad to hear putting CTRL-J to this useful purpose is OK with you. I'll push a change shortly.
